import {ConflictException,Injectable,UnauthorizedException} from "@nestjs/common";
import {JwtService} from "@nestjs/jwt";
import * as argon2 from "argon2";
import {createHash,randomUUID} from "crypto";
import {DatabaseService} from "../database/database.service";
import {Role} from "./auth.constants";
import {AuditService} from "../audit/audit.service";
type RefreshPayload={sub:string,role:Role,type:"refresh",jti:string,exp?:number};
type MeRow={id:string,email:string,role:Role,status:string,display_name:string|null,creator_display_name:string|null,handle:string|null};
type LoginRow={id:string,password_hash:string,role:Role,status:string};
@Injectable()
export class AuthService{
 constructor(private readonly db:DatabaseService,private readonly jwt:JwtService,private readonly audit:AuditService){}
 async register(email:string,password:string,role:Role,displayName:string){const normalized=email.trim().toLowerCase();const existing=await this.db.query("SELECT id FROM users WHERE email=$1",[normalized]);if(existing.rowCount)throw new ConflictException("Email already registered");const passwordHash=await argon2.hash(password,{type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1});const id=randomUUID();
  await this.db.transaction(async client=>{await client.query("INSERT INTO users(id,email,password_hash,display_name,role) VALUES($1,$2,$3,$4,$5)",[id,normalized,passwordHash,displayName.trim(),role]);if(role==="creator")await client.query("INSERT INTO creator_profiles(user_id,display_name,handle) VALUES($1,$2,$3)",[id,displayName.trim(),"creator_"+id.slice(0,8)]);});
  const tokens=await this.createSession(id,role);await this.audit.record({actorId:id,action:"AUTH_REGISTER",entityType:"user",entityId:id,metadata:{role}});return tokens;}
 async login(email:string,password:string){const result=await this.db.query<{id:string,password_hash:string,role:Role}>("SELECT id,password_hash,role FROM users WHERE email=$1",[email.trim().toLowerCase()]);const user=result.rows[0];if(!user||!(await argon2.verify(user.password_hash,password)))throw new UnauthorizedException("Invalid credentials");const tokens=await this.createSession(user.id,user.role);await this.audit.record({actorId:user.id,action:"AUTH_LOGIN",entityType:"user",entityId:user.id});return tokens;}
 async refresh(refreshToken:string){let payload:RefreshPayload;try{payload=await this.jwt.verifyAsync<RefreshPayload>(refreshToken,{secret:process.env.JWT_REFRESH_SECRET});}catch{throw new UnauthorizedException("Invalid refresh token");}if(payload.type!=="refresh"||!payload.sub||!payload.jti)throw new UnauthorizedException("Invalid refresh token");
  const tokens=await this.db.transaction(async client=>{const session=(await client.query<{user_id:string,role:Role,status:string,expires_at:Date,revoked_at:Date|null}>("SELECT rs.user_id,u.role,u.status,rs.expires_at,rs.revoked_at FROM refresh_sessions rs JOIN users u ON u.id=rs.user_id WHERE rs.id=$1 FOR UPDATE",[payload.jti])).rows[0];const tokenHash=this.hash(refreshToken);if(!session||session.status!=="ACTIVE"||session.revoked_at||session.expires_at.getTime()<=Date.now())throw new UnauthorizedException("Refresh session expired or revoked");const valid=(await client.query("SELECT 1 FROM refresh_sessions WHERE id=$1 AND token_hash=$2",[payload.jti,tokenHash])).rowCount>0;if(!valid)throw new UnauthorizedException("Refresh token reuse detected");await client.query("UPDATE refresh_sessions SET revoked_at=now() WHERE id=$1",[payload.jti]);const tokens=await this.signTokens(session.user_id,session.role);const decoded=this.jwt.decode(tokens.refreshToken) as RefreshPayload;await client.query("INSERT INTO refresh_sessions(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,to_timestamp($4))",[decoded.jti,session.user_id,this.hash(tokens.refreshToken),decoded.exp]);return tokens;});await this.audit.record({actorId:payload.sub,action:"AUTH_REFRESH",entityType:"refresh_session",entityId:(this.jwt.decode(tokens.refreshToken) as RefreshPayload).jti});return tokens;}
 async me(userId:string){const result=await this.db.query<MeRow>("SELECT u.id,u.email,u.role,u.display_name,cp.display_name AS creator_display_name,cp.handle FROM users u LEFT JOIN creator_profiles cp ON cp.user_id=u.id WHERE u.id=$1",[userId]);const user=result.rows[0];if(!user)throw new UnauthorizedException("User not found");return {id:user.id,email:user.email,role:user.role,displayName:user.display_name,creatorProfile:user.creator_display_name?{displayName:user.creator_display_name,handle:user.handle}:null};}
 async logout(userId:string,sessionId?:string){if(!sessionId)return {revoked:false};const result=await this.db.query("UPDATE refresh_sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE id=$1 AND user_id=$2",[sessionId,userId]);const revoked=(result.rowCount??0)>0;if(revoked)await this.audit.record({actorId:userId,action:"AUTH_LOGOUT",entityType:"refresh_session",entityId:sessionId});return {revoked};}
 private async createSession(userId:string,role:Role){const tokens=await this.signTokens(userId,role);const decoded=this.jwt.decode(tokens.refreshToken) as RefreshPayload;await this.db.query("INSERT INTO refresh_sessions(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,to_timestamp($4))",[decoded.jti,userId,this.hash(tokens.refreshToken),decoded.exp]);return tokens;}
 private async signTokens(userId:string,role:Role){const sessionId=randomUUID();const accessToken=await this.jwt.signAsync({sub:userId,role,jti:sessionId},{expiresIn:process.env.JWT_ACCESS_TTL??"15m"});const refreshToken=await this.jwt.signAsync({sub:userId,role,type:"refresh",jti:sessionId},{secret:process.env.JWT_REFRESH_SECRET,expiresIn:process.env.JWT_REFRESH_TTL??"30d"});return {accessToken,refreshToken,tokenType:"Bearer",expiresIn:process.env.JWT_ACCESS_TTL??"15m"};}
 private hash(token:string){return createHash("sha256").update(token).digest("hex");}
}