"use client";
import QrScanner from "../../components/qr-scanner";
import {useEffect,useState} from "react";
type FoodAlert={id:string;giftCode:string;creatorId:string;foodExpiryAt:string;status:string};
export default function Station(){
 const [id,setId]=useState("");const [msg,setMsg]=useState("");const [loading,setLoading]=useState(false);const [inspection,setInspection]=useState("CLEAR");const [notes,setNotes]=useState("");const [alerts,setAlerts]=useState<FoodAlert[]>([]);
 async function scan(){if(!id)return;setLoading(true);setMsg("");try{const r=await fetch("/api/station/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({giftId:id})});const data=await r.json();setMsg(data.sop?"Gift "+data.giftId+": "+data.status+" · "+data.sop:(data.message??"Gift not found"));}catch{setMsg("اتصال به API برقرار نشد.");}finally{setLoading(false);}}
 async function inspect(){if(!id)return;const r=await fetch("/api/station/inspection",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({giftId:id,status:inspection,notes})});const data=await r.json();setMsg(r.ok?"بازرسی بسته ذخیره شد.":"خطا: "+(data.message??"unknown error"));}
 useEffect(()=>{fetch("/api/station/food-alerts").then(r=>r.ok?r.json():[]).then(setAlerts).catch(()=>{});},[]);
 return <main className="mx-auto max-w-4xl px-6 py-12" dir="rtl"><h1 className="text-3xl font-bold">ایستگاه مرکزی</h1><p className="mt-2 text-neutral-600">اسکن شناسه/QR، بازرسی بسته و کنترل هدیه‌های غذایی.</p><div className="mt-8 rounded-2xl bg-white p-6 ring-1 ring-black/5"><div className="mb-5"><QrScanner onResult={(value)=>{const cleaned=value.replace(/^celebrity-gift:\/\//,"");setId(cleaned);setMsg("QR خوانده شد: "+cleaned);}}/></div><div className="flex gap-3"><input value={id} onChange={e=>setId(e.target.value)} placeholder="GFT-000184" className="flex-1 rounded-xl border p-3"/><button disabled={loading} onClick={scan} className="rounded-xl bg-black px-5 text-white disabled:opacity-50">{loading?"در حال بررسی…":"اسکن"}</button></div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_2fr]"><select value={inspection} onChange={e=>setInspection(e.target.value)} className="rounded-xl border p-3"><option value="CLEAR">سالم</option><option value="DAMAGED">آسیب‌دیده</option><option value="SUSPICIOUS">مشکوک</option><option value="REQUIRES_REPACK">نیازمند محافظ بیرونی</option></select><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} maxLength={1000} placeholder="یادداشت بازرسی" className="rounded-xl border p-3"/><button onClick={inspect} className="rounded-xl border px-4 py-2">ثبت بازرسی</button></div>{msg&&<p className="mt-5 rounded-xl bg-neutral-50 p-4">{msg}</p>}</div><section className="mt-8 rounded-2xl bg-white p-6 ring-1 ring-black/5"><h2 className="text-xl font-semibold">هشدار غذای نزدیک به انقضا</h2>{alerts.length===0?<p className="mt-4 text-sm text-neutral-500">هشدار فعالی نیست.</p>:<div className="mt-4 space-y-2">{alerts.map(a=><div key={a.id} className="rounded-xl bg-amber-50 p-4"><span className="font-medium">{a.giftCode}</span><span className="text-sm text-neutral-600"> · انقضا: {new Date(a.foodExpiryAt).toLocaleString("fa-IR")}</span></div>)}</div>}</section></main>;
}