"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
type Me={id:string;email:string;role:string;displayName:string|null;creatorProfile:{displayName:string;handle:string}|null};
type Notification={id:string;title:string;body:string;createdAt:string;readAt:string|null};
type Gift={id:string;giftCode:string;fanId:string;creatorId:string;category:string;status:string;food:boolean;fragile:boolean;foodExpiryAt:string|null};
const creatorActions=["ACCEPTED","DECLINED","RETURNED"];
export default function Dashboard(){
 const router=useRouter();const [me,setMe]=useState<Me|null>(null);const [notifications,setNotifications]=useState<Notification[]>([]);const [gifts,setGifts]=useState<Gift[]>([]);const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function load(){const [meRes,nRes,gRes]=await Promise.all([fetch("/api/auth/me",{cache:"no-store"}),fetch("/api/notifications",{cache:"no-store"}),fetch("/api/gifts",{cache:"no-store"})]);if(!meRes.ok)throw new Error("برای مشاهده داشبورد وارد شوید.");setMe(await meRes.json());if(nRes.ok)setNotifications(await nRes.json());if(gRes.ok)setGifts(await gRes.json());}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login");router.refresh();}
 async function changeStatus(id:string,status:string){const r=await fetch("/api/gifts/"+encodeURIComponent(id)+"/status",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});const d=await r.json();if(!r.ok){setMessage(Array.isArray(d.message)?d.message.join("، "):(d.message??"خطا"));return;}setMessage("وضعیت هدیه تغییر کرد.");await load();}
 return <main className="mx-auto max-w-6xl px-6 py-12" dir="rtl"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">داشبورد</h1><p className="mt-2 text-neutral-600">مدیریت حساب، احراز هویت، هدیه‌ها و اعلان‌ها.</p></div><button onClick={logout} className="rounded-xl border px-4 py-2">خروج</button></div>{error?<p className="mt-8 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>:me&&<>{message&&<p className="mt-4 rounded-xl bg-neutral-50 p-4">{message}</p>}<div className="mt-8 flex flex-wrap gap-3"><Link href="/verify" className="rounded-xl bg-black px-4 py-2 text-white">احراز هویت</Link>{me.role==="creator"&&<Link href="/discover" className="rounded-xl border px-4 py-2">پروفایل عمومی</Link>}</div><div className="mt-6 rounded-2xl bg-white p-6 ring-1 ring-black/5"><p className="text-sm text-neutral-500">حساب فعال</p><h2 className="mt-2 text-xl font-semibold">{me.displayName??me.email}</h2><p className="mt-1 text-sm text-neutral-500">نقش: {me.role}</p></div><section className="mt-6 rounded-2xl bg-white p-6 ring-1 ring-black/5"><div className="flex items-center justify-between"><h2 className="font-semibold">هدیه‌های من</h2><span className="text-sm text-neutral-500">{gifts.length} مورد</span></div>{gifts.length===0?<p className="mt-4 text-sm text-neutral-500">هنوز هدیه‌ای ثبت نشده است.</p>:<div className="mt-4 space-y-3">{gifts.slice(0,20).map(g=><div key={g.id} className="rounded-xl bg-neutral-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{g.giftCode} · {g.category}</span><span>{g.status}</span></div><p className="mt-2 text-sm text-neutral-500">{g.food?"غذا":""}{g.fragile?" · شکننده":""}{g.foodExpiryAt?" · انقضا: "+new Date(g.foodExpiryAt).toLocaleString("fa-IR"):""}</p>{me.role==="creator"&&g.status==="DELIVERED"&&<div className="mt-3 flex gap-2">{creatorActions.map(status=><button key={status} onClick={()=>changeStatus(g.id,status)} className="rounded-lg border px-3 py-1 text-sm">{status==="ACCEPTED"?"تایید":status==="DECLINED"?"رد":"برگشت"}</button>)}</div>}</div>)}</div>}</section><section className="mt-6 rounded-2xl bg-white p-6 ring-1 ring-black/5"><div className="flex items-center justify-between"><h2 className="font-semibold">اعلان‌ها</h2><span className="text-sm text-neutral-500">{notifications.filter(n=>!n.readAt).length} خوانده‌نشده</span></div>{notifications.length===0?<p className="mt-4 text-sm text-neutral-500">اعلان جدیدی ندارید.</p>:<div className="mt-4 space-y-3">{notifications.slice(0,8).map(n=><div key={n.id} className={"rounded-xl p-4 "+(n.readAt?"bg-neutral-50":"bg-blue-50")}><p className="font-medium">{n.title}</p><p className="mt-1 text-sm text-neutral-600">{n.body}</p></div>)}</div>}</section></>}</main>;
}