"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Creator={id:string;displayName:string;handle:string;category:string|null;interestIndicator?:string;isMember?:boolean;uniqueFans?:number};
export default function Discover(){
 const [search,setSearch]=useState("");const [creators,setCreators]=useState<Creator[]>([]);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();setLoading(true);Promise.all([
  fetch((process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000")+"/api/creators?search="+encodeURIComponent(search),{signal:controller.signal,cache:"no-store"}),
  fetch((process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000")+"/api/creator-interests?search="+encodeURIComponent(search),{signal:controller.signal,cache:"no-store"})
 ]).then(async([a,b])=>{const members=await a.json();const targets=await b.json();const memberList=(Array.isArray(members)?members:[]).map((x:any)=>({...x,isMember:true}));const targetList=(Array.isArray(targets)?targets:[]).map((x:any)=>({...x,isMember:false}));const map=new Map<string,Creator>();for(const item of [...memberList,...targetList])map.set(item.handle,item);setCreators([...map.values()]);}).catch(()=>{}).finally(()=>setLoading(false));return()=>controller.abort();},[search]);
 async function expressInterest(c:Creator){setMessage("");const r=await fetch("/api/creator-interests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({handle:c.handle,displayName:c.displayName,category:c.category})});const data=await r.json();setMessage(r.ok?"علاقه شما ثبت شد و در شمارش یکتای این Creator لحاظ می‌شود.":(Array.isArray(data.message)?data.message.join("، "):(data.message??"برای ثبت علاقه ابتدا وارد شوید.")));}
 return <main className="mx-auto max-w-5xl px-6 py-14" dir="rtl"><h1 className="text-3xl font-bold">پیدا کردن کرییتور</h1><p className="mt-2 text-neutral-600">آدرس خصوصی و اطلاعات احراز هویت هیچ کرییتوری عمومی نیست.</p><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجو بر اساس نام یا handle" className="mt-6 w-full rounded-xl border p-3"/>{message&&<p className="mt-4 rounded-xl bg-neutral-50 p-4 text-sm">{message}</p>}{loading?<p className="mt-8 text-neutral-500">در حال دریافت…</p>:<div className="mt-8 grid gap-4 md:grid-cols-3">{creators.map(c=><article key={c.handle} className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><div className="h-12 w-12 rounded-full bg-neutral-200"/><h2 className="mt-4 font-semibold">{c.displayName}</h2><p className="text-sm text-neutral-500">@{c.handle} · {c.category??"بدون دسته‌بندی"}</p>{c.interestIndicator&&<p className="mt-4 text-sm text-neutral-600">{c.interestIndicator}</p>}{c.isMember?<Link href={"/gifts/request?creator="+encodeURIComponent(c.id)} className="mt-5 inline-block rounded-lg bg-black px-4 py-2 text-sm text-white">درخواست هدیه</Link>:<button onClick={()=>expressInterest(c)} className="mt-5 rounded-lg border px-4 py-2 text-sm">ثبت علاقه</button>}</article>)}</div>}</main>;
}