"use client";
import {FormEvent,useEffect,useState} from "react";
import {useSearchParams,useRouter} from "next/navigation";
export default function GiftRequest(){
 const params=useSearchParams();const router=useRouter();const creatorId=params.get("creator")??"";
 const [quote,setQuote]=useState<any>(null);const [categories,setCategories]=useState<string[]>([]);const [msg,setMsg]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{Promise.all([fetch("/api/courier/quote",{cache:"no-store"}),fetch("/api/catalog",{cache:"no-store"})]).then(async([q,c])=>{if(q.ok)setQuote(await q.json());if(c.ok){const x=await c.json();setCategories(Array.isArray(x.giftCategories)?x.giftCategories:[]);}}).catch(()=>{});},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMsg("");const form=new FormData(e.currentTarget);try{const food=form.get("food")==="on";const r=await fetch("/api/gifts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({creatorId,category:form.get("category"),food,fragile:form.get("fragile")==="on",noteDeclared:form.get("noteDeclared")==="on",foodExpiryAt:food?form.get("foodExpiryAt")||undefined:undefined})});const data=await r.json();if(!r.ok)throw new Error(Array.isArray(data.message)?data.message.join("، "):(data.message??"درخواست هدیه ثبت نشد"));setMsg("هدیه ثبت شد: "+data.giftCode);router.push("/dashboard");router.refresh();}catch(e){setMsg(e instanceof Error?e.message:"خطا در ثبت هدیه");}finally{setLoading(false);}}
 const labels:Record<string,string>={clothing:"لباس",book:"کتاب",letter:"نامه",handmade:"دست‌ساز",food:"غذا",fragile:"شکننده",other:"سایر"};
 return <main className="mx-auto max-w-xl px-6 py-12" dir="rtl"><h1 className="text-3xl font-bold">درخواست هدیه</h1><p className="mt-2 text-neutral-600">Creator: {creatorId||"نامشخص"}</p><form onSubmit={submit} className="mt-8 space-y-4 rounded-2xl bg-white p-6 ring-1 ring-black/5"><select name="category" required className="w-full rounded-xl border p-3">{categories.map(c=><option key={c} value={c}>{labels[c]??c}</option>)}</select><label className="flex gap-2"><input name="food" type="checkbox"/> این هدیه غذاست</label><label className="flex gap-2"><input name="fragile" type="checkbox"/> شکننده است</label><label className="flex gap-2"><input name="noteDeclared" type="checkbox"/> داخل بسته نامه/یادداشت هست</label><label className="block"><span className="mb-2 block text-sm">تاریخ انقضای غذا (در صورت اعلام غذا)</span><input name="foodExpiryAt" type="datetime-local" className="w-full rounded-xl border p-3"/></label><div className="rounded-xl bg-neutral-50 p-4 text-sm">هزینه تقریبی: {quote?quote.totalInr+" INR":"در حال محاسبه…"}</div><button disabled={loading||!creatorId||categories.length===0} className="w-full rounded-xl bg-black p-3 text-white disabled:opacity-50">{loading?"در حال ثبت…":"ثبت درخواست"}</button></form>{msg&&<p className="mt-4 rounded-xl bg-red-50 p-4">{msg}</p>}</main>;
}