import {BadRequestException,Injectable,ServiceUnavailableException} from "@nestjs/common";
import {randomUUID} from "crypto";
import {KycProvider,KycSubmission} from "./kyc.provider";
import type {VerificationStatus} from "./verification.service";
type DocType="aadhaar"|"pan"|"passport"|"voter_id"|"driving_license";
@Injectable()
export class HyperVergeKycProvider implements KycProvider{
 async submit(input:KycSubmission){const appId=process.env.HYPERVERGE_APP_ID;const appKey=process.env.HYPERVERGE_APP_KEY;if(!appId||!appKey)throw new ServiceUnavailableException("HyperVerge credentials are not configured");const transactionId=randomUUID();const ocrUrl=this.ocrUrl(input.documentType);const form=new FormData();form.append("file",new Blob([input.document.buffer],{type:input.document.mimeType}),input.document.fileName);const ocr=await this.call(ocrUrl,form,appId,appKey,transactionId);if(!ocr.ok)throw new BadRequestException("Identity document could not be verified");let faceMatchPassed=false;try{const faceForm=new FormData();faceForm.append("selfie",new Blob([input.selfie.buffer],{type:input.selfie.mimeType}),input.selfie.fileName);faceForm.append("id",new Blob([input.document.buffer],{type:input.document.mimeType}),input.document.fileName);const face=await this.call(process.env.HYPERVERGE_FACE_MATCH_URL??"https://ind.idv.hyperverge.co/v1/matchFace",faceForm,appId,appKey,transactionId);faceMatchPassed=face.ok&&this.faceMatch(face.body);}catch{faceMatchPassed=false;}
  let livenessPassed:boolean|null=null;if(process.env.HYPERVERGE_LIVENESS_URL){try{const liveForm=new FormData();liveForm.append("selfie",new Blob([input.selfie.buffer],{type:input.selfie.mimeType}),input.selfie.fileName);const live=await this.call(process.env.HYPERVERGE_LIVENESS_URL,liveForm,appId,appKey,transactionId);livenessPassed=live.ok&&this.livenessMatch(live.body);}catch{livenessPassed=false;}}
  const status:VerificationStatus=faceMatchPassed&&livenessPassed===true?"AUTO_VERIFIED":"MANUAL_REVIEW";return {provider:"hyperverge",reference:transactionId,status,livenessPassed,faceMatchPassed,providerScore:this.score(ocr.body,faceMatchPassed,livenessPassed)};}
 private ocrUrl(type:DocType){const map:Record<DocType,string>={aadhaar:process.env.HYPERVERGE_AADHAAR_OCR_URL??"https://ind-docs.hyperverge.co/v2.0/readAadhaar",pan:process.env.HYPERVERGE_PAN_OCR_URL??"https://ind-docs.hyperverge.co/v2.0/readPAN",passport:process.env.HYPERVERGE_PASSPORT_OCR_URL??"https://ind-docs.hyperverge.co/v2.0/readPassport",voter_id:process.env.HYPERVERGE_VOTER_OCR_URL??"https://ind-docs.hyperverge.co/v2.0/readVoterID",driving_license:process.env.HYPERVERGE_DL_OCR_URL??"https://ind-docs.hyperverge.co/v2.0/readDL"};return map[type];}
 private async call(url:string,form:FormData,appId:string,appKey:string,transactionId:string){const response=await fetch(url,{method:"POST",headers:{appId,appKey,transactionId},body:form});const body=await response.text();let parsed:any;try{parsed=JSON.parse(body);}catch{parsed={raw:body};}return {ok:response.ok,body:parsed};}
 private faceMatch(body:any){return Boolean(body?.result?.match??body?.result?.isMatch??body?.match??body?.isMatch);}
 private livenessMatch(body:any){return Boolean(body?.result?.liveness??body?.result?.isLive??body?.liveness??body?.isLive);}
 private score(body:any,face:boolean,live:boolean|null){const raw=Number(body?.result?.score??body?.score);if(Number.isFinite(raw))return Math.max(0,Math.min(100,raw));return face&&live===true?100:undefined;}
}